language: android
#jdk: oraclejdk8
dist: trusty
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-30.0.2

  # The SDK version used to compile your project
  - android-30

  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository

# Travis Ci를 어느 브랜치가 푸시될 때 수행할지 지정
branches: 
  only:
    - master

before_install:
- chmod +x gradlew
- chmod +rx app 
skip_cleanup: true
script: 
  - "sh script/build.sh"
deploy:
  provider: script
  skip_cleanup: true
  script: "sh script/deploy.sh"
  on:
    branch:
      - dev
      - master

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hamdoyoung95@gmail.com 
  slack: doyounghq:SMfozRdOZAl8uyWVqEl2pyqR
    on_success: always
    on_failure: always